In [15]:
import numpy as np
import random

In [16]:
g = 1 # gamma discounting rate
r_s = -1 #reward size
g_s = 4 #grid size
t_s = [[0,0], [g_s-1, g_s-1]] #termination states
a = [[-1, 0], [1, 0], [0, 1], [0, -1]] #actions
i = 100 #iterations

In [17]:
def actionRewardFunction(i, a): #i is the intial position and a is action
    
    if i in t_s:
        return i, 0
    
    r = r_s #reward
    f = np.array(i) + np.array(a) #final
    if -1 in f or 4 in f: 
        f = i
        
    return f, r

In [18]:
valuemap = np.zeros((g_s, g_s))
states = [[ii, jj] for ii in range(g_s) for jj in range(g_s)]

In [19]:
valuemap

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
deltas = []
for it in range(i):
    cvaluemap = np.copy(valuemap)
    dstate = []
    for s in states:
        w_r = 0 #weighted rewards
        for ai in a:
            f, r = actionRewardFunction(s, ai)
            w_r += (1/len(a))*(r+(g*valuemap[f[0], f[1]]))
        dstate.append(np.abs(cvaluemap[s[0], s[1]]-w_r))
        cvaluemap[s[0], s[1]] = w_r
    deltas.append(dstate)
    valuemap = cvaluemap
    if it in [0,1,2,9, i-1]:
        print("Iteration {}".format(it+1))
        print(valuemap)
        print("")

Iteration 1
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]

Iteration 2
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]

Iteration 3
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]

Iteration 10
[[ 0.         -6.13796997 -8.35235596 -8.96731567]
 [-6.13796997 -7.73739624 -8.42782593 -8.35235596]
 [-8.35235596 -8.42782593 -7.73739624 -6.13796997]
 [-8.96731567 -8.35235596 -6.13796997  0.        ]]

Iteration 100
[[  0.         -13.94260509 -19.91495107 -21.90482522]
 [-13.94260509 -17.92507693 -19.91551999 -19.91495107]
 [-19.91495107 -19.91551999 -17.92507693 -13.94260509]
 [-21.90482522 -19.91495107 -13.94260509   0.        ]]

